### Why Python programming?
#### High readability

In [1]:
print("I love python and machine learning.\n" * 5)

I love python and machine learning.
I love python and machine learning.
I love python and machine learning.
I love python and machine learning.
I love python and machine learning.



### Introduction to Jupyter Notebook 
Two modes: **edit mode** and **command mode**.

#### Edit mode
Edit mode: Click in the cell and edit; green border

To run a code cell in edit mode: Ctrl+enter (windows); control+return (Mac)

Once a code cell is executed, there will be a number appearing in the square bracket in front of the cell, indicating the sequence of executing cells.

If it is $*$ in the square bracket, it means the code is running for long, possibly has frozen

#### Command mode
Command mode: Click the white space in front of the cell; blue border
Keyboard shortcuts
- <code>A</code>: insert a cell above
- <code>B</code>: insert a cell below
- <code>D</code>, <code>D</code>: delete a cell
- <code>M</code>: change to markdown mode
- <code>Y</code>: change to code mode

In [2]:
print(10)

10


### Variable

In [3]:
a = 10
print(a)

10


In [4]:
a = a - 2
print(a)

8


What happens to ‘print’ if it is used as a var name? 

In [5]:
# after you run this cell, make sure you restart kernel
print = 5
print(10)

TypeError: 'int' object is not callable

### Data Type

In [6]:
x = 1
type(x)

int

In [7]:
y = 1.02
type(y)

float

In [8]:
likes_TV = True        
likes_sushi = False
type(likes_TV)
type(likes_sushi)

bool

In [9]:
s = 'banana'           
s = "banana"
type(s)

str

In [10]:
name_list = ['John', 'Jane']
type(name_list)

list

In [11]:
contacts = {'John':66666666, 'Jane':77777777}
type(contacts)

dict

### Comparison operators 
<code><   >=   <=   ==   != <!code>


In [12]:
print(5 >= 5)

TypeError: 'int' object is not callable

In [13]:
print(4 != 4)

TypeError: 'int' object is not callable

In [14]:
print(4 == 4)

TypeError: 'int' object is not callable

In [15]:
a = 2
b = 3
print(a > b)

TypeError: 'int' object is not callable

### Logical operators 
<code>and   or   not <!code>

In [16]:
a = 6
b = 5
c = 0
print(a > b and a == c)
print(a > b or a == c)
print(not a > b)

TypeError: 'int' object is not callable

In [18]:
print(a < 10 or a > 5)

TypeError: 'int' object is not callable

### Control flow if-elif-else

In [19]:
age = 40
status = "single"

if age >= 35:
    print("you are at least 35 years old")
    print("you can buy a HDB flat")
elif status == 'married' and age >= 21:
    print("you can buy a HDB flat")
else:
    print("wait a few more years")

TypeError: 'int' object is not callable

In [20]:
age = 33
x = "old" if age >= 32 else "young"
print(x)

TypeError: 'int' object is not callable

write the above with a normal if-else:

In [21]:
if age >= 32:
    x = "old"
else:
    x = "young"
print(x)

TypeError: 'int' object is not callable

### Function

In [22]:
age = 40
print(age)

TypeError: 'int' object is not callable

In [23]:
age = 40
type(age)

int

print() does not return a result for the assignment

In [24]:
age = 40
x = print(age)
print(x)

TypeError: 'int' object is not callable

type() does return a result for the assignment

In [25]:
age = 40
x = type(age)
print(x)

TypeError: 'int' object is not callable

### String

In [26]:
s = 'banana'
s[2]

'n'

In [27]:
s[2:5]

'nan'

in:  boolean operator

In [28]:
s = "BANANA"
s in "banana republic"

False

+: string concatenation

In [29]:
x = s + "republic"
print(x)

TypeError: 'int' object is not callable

### List

In [30]:
name_list = ['John', 'Jane']
name_list[1]

'Jane'

In [31]:
len(name_list)

2

In [32]:
name_list[0:1]

['John']

in:  boolean operator

In [33]:
'Jay' in name_list

False

+: list concatenation

In [34]:
s = name_list + ['Jay', 'Joe']

In [35]:
[1,2] + [3,4]

[1, 2, 3, 4]

### Dictionary

In [36]:
contacts = {'John':66666666, \
            'Jane':77777777}
print(contacts['John']) 

TypeError: 'int' object is not callable

In [37]:
contacts['John'] = 88888888
print(contacts)

TypeError: 'int' object is not callable

In [38]:
contacts['Joe'] = 99999999 
print(contacts)

TypeError: 'int' object is not callable

In [39]:
{'John':66666666, 'Jane':77777777} == {'Jane':77777777, 'John':66666666}

True

In [40]:
[1,2] == [2,1]

False

### Python libraries

In [41]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install scikit-learn

### numpy ndarray

In [42]:
import numpy as np
arr_1d = np.array([10, 20, 30])
arr_1d

array([10, 20, 30])

In [43]:
arr_1d.ndim

1

In [44]:
arr_2d = np.array([   [10,20], [30,40], [50,60]    ])
arr_2d

array([[10, 20],
       [30, 40],
       [50, 60]])

In [45]:
arr_2d.ndim

2

In [46]:
arr_3d = np.array([arr_2d, arr_2d, arr_2d])
arr_3d

array([[[10, 20],
        [30, 40],
        [50, 60]],

       [[10, 20],
        [30, 40],
        [50, 60]],

       [[10, 20],
        [30, 40],
        [50, 60]]])

Attributes (not functions)

In [47]:
print(arr_3d.ndim)
print(arr_3d.shape)
print(arr_3d.size)
print(arr_3d.dtype)

TypeError: 'int' object is not callable

Slicing

In [48]:
arr_1d[0]

10

In [49]:
arr_1d[0:2]

array([10, 20])

In [50]:
arr_2d

array([[10, 20],
       [30, 40],
       [50, 60]])

In [51]:
arr_2d[0, 0]

10

In [52]:
arr_2d[0:2, 0:1]

array([[10],
       [30]])

In [53]:
arr_2d

array([[10, 20],
       [30, 40],
       [50, 60]])

Statistical functions - ndarray methods

In [54]:
arr_2d.mean()

35.0

In [55]:
arr_2d.std()

17.07825127659933

Statistical functions - Numpy library functions

In [56]:
np.mean(arr_2d)

35.0

In [57]:
np.std(arr_2d)

17.07825127659933

In [58]:
np.percentile(arr_2d, 20)  #20th-percentile

20.0

In [59]:
np.percentile(arr_2d, 50)  #50th-percentile
# Is this mean or median?

35.0

Element-wise operations

In [60]:


x = np.array([10, 20, 30])
x2 = x + 10
print(x2)

y = x + x
print(y)

z = x * x
print(z)

TypeError: 'int' object is not callable

Broadcasting

In [61]:
arr_2d = np.array([[10,20], [30,40], [50,60]])
x + arr_2d   # does this work?

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [62]:
arr_2d = np.array([[10,20,30], [30,40,50]])
x + arr_2d   # does this work?

array([[20, 40, 60],
       [40, 60, 80]])

### pandas Series

In [70]:
import pandas as pd
age = pd.Series([2,4,1])

Attributes

In [71]:
print(age.index)
print(age.values)

TypeError: 'int' object is not callable

In [65]:
print(age)

TypeError: 'int' object is not callable

index can be modified to meaningful labels

In [69]:
age.index = ['Milo','Coco','Lulu']
print(age)

TypeError: 'int' object is not callable

Two ways to access an item of a Series

In [67]:
print(age[0])
print(age['Milo'])

TypeError: 'int' object is not callable

Slice a Series with a slice of indices

In [68]:
# are below the same?
print(age[0:1]) 
print(age['Milo':'Coco'])

TypeError: 'int' object is not callable

### pandas DataFrame

In [ ]:
# Prices of 3 stocks in 3 days
stock = pd.DataFrame({"TSLA": [122.72, 123.08, 122.94],
                      "FB":[3220.08, 3203.53, 3186.73],
                      "GOOG":[584.76, 568.82, 593.38]})
stock.index = ['2021-01-01','2021-01-02','2021-01-03']
display(stock)

Attributes

In [ ]:
print(stock.columns)
print(stock.index)
print(stock.shape)
print(stock.size)

Edit the row index to be more meaningful

In [ ]:
stock.index = ['2021-01-01', '2021-01-02', '2021-01-03'] 
display(stock)

Read column(s) with []

In [ ]:
tsla = stock['TSLA']
print(tsla)

In [ ]:
subset = stock[['TSLA','GOOG']]
display(subset)

indexer loc[] and iloc[]

In [ ]:
stock

In [ ]:
print(stock.loc['2021-01-01', 'TSLA'])
display(stock.loc[['2021-01-01','2021-01-03'], ['GOOG','TSLA']])
display(stock.loc['2021-01-01':'2021-01-02','TSLA':'GOOG'])
# Q: Is the ending index inclusive?

In [ ]:
stock['TSLA']

In [ ]:
print(stock.iloc[1, 1])
display(stock.iloc[[0,2], [0,2]])
display(stock.iloc[0:1, 0:1])
# Q: Is the ending index inclusive?

Conditional operations

In [ ]:
display(stock > 123)

In [ ]:
display(stock['TSLA'] > 123)

Boolean indexing with .loc[]

In [ ]:
display(stock.loc[   stock['TSLA'] > 123   ])

In [ ]:
display(stock.loc[  (stock['TSLA'] < 123) & (stock['GOOG'] > 590)  ])

In [ ]:
display(stock.loc[(stock['FB'] > 3200) | (stock['FB'] < 3180)])

file read and write

In [ ]:
stock.to_csv('stock.csv')
stock.to_excel('stock.xlsx')

In [ ]:
stock2 = pd.read_csv('stock.csv')
display(stock2)

In [ ]:
stock3 = pd.read_excel('stock.xlsx')
display(stock3)

Add an argument to specify which column to use as row index

In [ ]:
stock2 = pd.read_csv('stock.csv', index_col = 0)
display(stock2)

In [ ]:
stock3 = pd.read_excel('stock.xlsx', index_col = 0)
display(stock3)

Ensure that csv or excel is in the same folder as the code (.ipynb file), or the correct file path is given

In [ ]:
stock3 = pd.read_excel('datasets\\stock.xlsx', index_col = 0) # windows
# from current folder of the .ipynb file, we need to get into datasets sub-folder, where stock.xlsx is
display(stock3)

In [ ]:
stock3 = pd.read_excel('datasets/stock.xlsx', index_col = 0) # Mac
# from current folder of the .ipynb file, we need to get into datasets sub-folder, where stock.xlsx is
display(stock3)

## scikit-learn

$$
explained\_variance\_score(\hat{y},y) = 1 - \frac{Var(y- \hat{y})}{Var(y)} 
$$

In [72]:
from sklearn.metrics import explained_variance_score
y_hat = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
explained_variance_score(y_hat, y_pred)

0.9571734475374732